<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-desktop;net10.0-browserwasm</TargetFrameworks>

    <OutputType>Exe</OutputType>
    <DefineConstants>$(DefineConstants);IS_WINUI</DefineConstants>
    <UnoSingleProject>true</UnoSingleProject>

    <!-- Display name -->
    <ApplicationTitle>SnackbarTestApp</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>com.companyname.snackbartestapp</ApplicationId>
    <!-- Versions -->
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <!-- Package Publisher -->
    <ApplicationPublisher>SnackbarTestApp</ApplicationPublisher>
    <!-- Package Description -->
    <Description>SnackbarTestApp powered by Uno Platform.</Description>

    <!--
      UnoFeatures are used to quickly add and manage features enabled for your app.
      https://aka.platform.uno/singleproject-features
    -->
    <UnoFeatures>
      Material;
      Toolkit;
      SkiaRenderer;
    </UnoFeatures>
  </PropertyGroup>

</Project>
