<Project Sdk="Uno.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-desktop</TargetFramework>

        <OutputType>Exe</OutputType>
        <UnoSingleProject>true</UnoSingleProject>


        <!-- Display name -->
        <ApplicationTitle>MPE</ApplicationTitle>
        <!-- App Identifier -->
        <ApplicationId>com.companyname.MPE</ApplicationId>
        <!-- Versions -->
        <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
        <ApplicationVersion>1</ApplicationVersion>
        <!-- Package Publisher -->
        <ApplicationPublisher>O=MPE</ApplicationPublisher>
        <!-- Package Description -->
        <Description>MPE powered by Uno Platform.</Description>

        <!--
          UnoFeatures let's you quickly add and manage implicit package references based on the features you want to use.
          https://aka.platform.uno/singleproject-features
        -->
        <UnoFeatures>
            Material;
            Dsp;
            Toolkit;
            Mvvm;
            ThemeService;
            MediaElement;
            SkiaRenderer;
        </UnoFeatures>
    </PropertyGroup>

</Project>
